{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    codefresh.io.refresh: "{{ .Values.codefresh.refresh}}"
    kubernetes.io/ingress.class:  nginx
    nginx.org/redirect-to-https: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
     - http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  tls:
         - secretName: {{ .Release.Name }}-codefresh-star-selfsigned
    
  {{- end -}}

