apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: {{name}}
spec:
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: echo
    ports:
    - containerPort: 3333
      protocol: TCP

