apiVersion: v1
kind: Service
metadata:
  name: {{metadata.name}}
  labels:
    app: {{metadata.labels.app}}
  annotations : 
    codefresh.io.refresh: {{metadata.annotations.refresh}}
spec:
  type: {{spec.type}}
  ports:
    - port: {{ spec.service.externalPort }}
      targetPort: {{spec.service.internalPort }}
      protocol: TCP
      name: {{spec.service.portname }}
  selector:
    app: {{metadata.labels.app}}
    release: {{release.Name }}
