# Default values for minimalKube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
codefresh: 
   refresh: 8
image:
  repository: verchol/kubeintegration
  tag: latest
  pullPolicy: Always
service:
  name: entitymanager
  type: LoadBalancer
  #type: ClusterIP
  externalPort: 80
  internalPort: 8888

ingress:
  enabled: true
  # specify host
  host: codefresh.dev
  #specify path
  # IMPORTANT!!!
  # - GCE requires * at the end
  # - Nginx requires no star
  path: /kube/
  
  # Used to create an Ingress record
  annotations:
    # GCE Ingress Controller
    # kubernetes.io/ingress.class: "gce"
    # Nginx Ingress controller (default)
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/redirect-to-https: "false"
    # Other Ingress settings
    # kubernetes.io/tls-acme: "true"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
